platform :ios, '7.0'
pod 'MBProgressHUD', '~> 0.9'
pod 'IQKeyboardManager'
pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage', '~>3.8'
pod 'PEPhotoCropEditor'
pod 'Charts'
platform :ios, '8.0'
use_frameworks!
pod 'PermissionScope'
